### ISSUE TITLE
Serial: Add support for setting up baudrate

### ISSUE THREAD

**Issue by DhruvaG2000** [zephyrproject-rtos/gsoc-2022-arduino-core#42]
inside Serial.begin() we can implement baudrate perhaps using:
- [uart_config Struct ](https://docs.zephyrproject.org/latest/hardware/peripherals/uart.html)
- [UART controller config structure](https://docs.zephyrproject.org/latest/hardware/peripherals/uart.html)

**Comment by soburi** [comment]
@DhruvaG2000 
This issue may solve with #64.
Could you confirm it?

**Comment by DhruvaG2000** [comment]
@soburi thanks for the reminder,
I tested on arduino nano 33 ble sense, with 9600 and 115200 baudrates, setting the baudrate in setup does indeed reflect in reality.
Hence, closing this.
