### ISSUE TITLE
Implementing SPI library

### ISSUE THREAD

**Issue by soburi** [zephyrproject-rtos/gsoc-2022-arduino-core#87]
We need to implement the SPI library to keep it compatible with standard AVR Arduino.

**Comment by DhruvaG2000** [comment]
Just documenting further details here,
1. [SPI.h arduino API](https://www.arduino.cc/reference/en/language/functions/communication/spi/)
2. [Zephyr SPI API](https://docs.zephyrproject.org/apidoc/latest/group__spi__interface.html)

**Comment by DhruvaG2000** [comment]
> SPI should be included when writing a device overlay, but I'm not in a position to test it.

@soburi  I could probably test the SPI implementation if you're able to raise a PR for SPI using ADXL355 sensor or something that I may have access to.

https://github.com/plasmapper/adxl355-arduino
This should be a good library to validate SPI works. Let me know if you are interested, I can definitely help but will be difficult for me to implement fully at the moment.
